version: 2
jobs:
  build:
    working_directory: /go/src/github.com/crifff/gae-sample
    docker:
      - image: golang:1.6.3
    steps:
      - checkout
      - run: echo $GOPATH
      - run:
          name: run test
          command: go test ./...
