version: 2
jobs:
  build:
    working_directory: /go/src/github.com/crifff/gae-sample
    docker:
      - image: circleci/cci-demo-go-primary:0.0.2
        environment:
          PROJECT_ROOT: /go/src/github.com/crifff/gae-sample
          PATH: "${PATH}:${GOPATH}/bin:/go_appengine/bin:${PROJECT_ROOT}/node_modules/.bin"
    steps:
      - checkout
      - run:
          name: install SDK
          command: curl -o $HOME/go_appengine_1.9.48.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.48.zip && unzip -q -d / $HOME/go_appengine_1.9.48.zip
      - run: echo $GOPATH
      - run:
          name: run test
          command: goapp test ./...
