version: 2
jobs:
  build:
    working_directory: ~/sample_goapp
    docker:
      - image: criff/goapp-docker
    steps:
      - checkout
      - run:
          name: run test
          command: goapp test ./...